#!/bin/bash

# FORMATING VARIABLE
bold=$(tput bold)
# italic=$(tput italic)
normal=$(tput sgr0)

# set defaults
INPUT=0
COLORS=16
OUTPUT="palette.png"

show_help(){
echo "--------------------------------------------"
echo "Get dominant colors"
echo ""
echo "${bold}-i | --input  |${normal} Input name"
echo "${bold}-o | --output |${normal} Output name (default palette.png)"
echo "${bold}-c | --colors |${normal} Number of colors (default 16)"
echo ""
echo "Example : palette img.png -c 16 -o palette.png"
echo ""
echo "--------------------------------------------"
}


# handle flags
while [[ $# -gt 0 ]]; do
    case "$1" in
        -i|--input)
            shift; INPUT="$1"
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        -o|--output)
        shift; OUTPUT="$1" 
        ;;
        -c|--colors)
        shift; COLORS=$1
        ;;
        *)
            echo "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
    shift
done

# speed up process by reducing image size
magick $INPUT -sample 10% temp.png

TEST_VARIABLE=`magick temp.png -format %c -colorspace LAB -colors $COLORS histogram:info:- | sort -n -r | tr ' ' '\n' | sed -n '/^srgb/p' | tr ' ' '\r'`

rm temp.png

images=()
for ((i=1; i<=COLORS; i++)); do
    color=$(echo "$TEST_VARIABLE" | sed -n "${i-1}p")
    images+=("xc:\"$color\"")
done

# create picture where each pixel is one of the colors
eval magick -size 60x60 "${images[@]}" +append $OUTPUT